services:
  - type: worker
    name: yandex-bot-worker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8703950276:AAGP5RX0Ib7cLBgFKJPMjqnA2dtbDuLaknk
      - key: ADMIN_ID
        value: 8394493239
